**Write a program to convert a list and tuple into arrays**

Method 1

In [36]:
import numpy as np

# Declare List Elements
my_list = []

**Flatten Method**

In [37]:
import numpy as np

a = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
b = a.flatten()  # b = a.flatten('C')
print(b)
c = a.flatten("F")  # F is column wise
print(c)
d = a.flatten("A")
print(d)
e = a.flatten("K")
print(e)

[1 4 7 2 5 8 3 6 9]
[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]
[1 4 7 2 5 8 3 6 9]


**Array of Zeroes**

In [38]:
import numpy as np

np.zeros(5)
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**Array of Ones**

In [39]:
import numpy as np

np.ones(5, dtype=np.int32)

array([1, 1, 1, 1, 1])

**Array of random numbers**

In [40]:
import numpy as np

np.random.rand(2, 3)

array([[0.51630785, 0.47659755, 0.47182476],
       [0.89798271, 0.23194195, 0.61405087]])

**Addition of two matrices**

In [41]:
import numpy as np

A = np.array([[2, 4], [5, 6]])
B = np.array([[9, -3], [3, 6]])
C = A + B
print(C)

[[11  1]
 [ 8 12]]


**Matrix Multiplication**

In [42]:
import numpy as np

A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)

[[ 36 -12]
 [ -1   2]]


**Transpose Matrix**

In [43]:
import numpy as np

A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

[[ 1  2  3]
 [ 1  1 -3]]


**Strings and Characters**

In [44]:
str1 = "Hello Python"
print(str1)
str2 = "Hello Pyhton"
print(str2)
str3 = """Hello World"""
print(str3)

Hello Python
Hello Pyhton
Hello World


**Operation on Strings**

In [45]:
str1 = "Hello"
str2 = "World!"
print("str1 + str 2 = ", str1 + str2)
print("str1 * 3 = ", str1 * 3)

str1 + str 2 =  HelloWorld!
str1 * 3 =  HelloHelloHello


**String Length**

In [46]:
a = "Hello World!"
print(len(a))

12


**Looping**

In [47]:
for x in "banana":
    print(x)

b
a
n
a
n
a


**String Membership Test**

In [48]:
print("a" in "program")
print("at" not in "battle")

True
False


**String Indexing and Splitting**

In [49]:
str = "Hello"
print(str[:5])
print(str[:])
print(str[-3:-1])
print(str[::-1])

Hello
Hello
ll
olleH


**Working with Characters**

In [50]:
"abc123".isalnum()

True

In [51]:
"ab&123".isalnum()

False

In [52]:
"".isalnum()

False

In [53]:
'dssdf'.isalpha()

True

In [54]:
'123'.isdigit()

True

In [55]:
'123abc'.isdigit()

False

In [56]:
'abc'.islower()

True

In [57]:
'abc1$d'.islower()

True

In [58]:
'Abc1$D'.islower()

False

In [59]:
'ABC'.isupper()

True

In [60]:
'Abc1$D'.isupper()

False

In [65]:
a = ('b', 'g', 'a', 'd', 'f', 'c', 'h', 'e', '', ' ')
x = sorted(a)
print(x)
x = sorted(a, reverse=True)
print(x)

['', ' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ' ', '']


In [67]:
str = 'I like to sort'
x = sorted(str)
print(x)

[' ', ' ', ' ', 'I', 'e', 'i', 'k', 'l', 'o', 'o', 'r', 's', 't', 't']


**Split Method**

In [70]:
s = 'i like to sort'
print(s.split())
print(sorted(s.split()))
g = ''.join(s)
h = sorted(s.split())
g2 = ''.join(h)
print(g2)
print(g)

['i', 'like', 'to', 'sort']
['i', 'like', 'sort', 'to']
ilikesortto
i like to sort


In [71]:
text = 'Hello, Welcome to my world.'
x = text.find("Welcome")
print(x)

7


In [72]:
text = 'Hello, Welcome to my world.'
x = text.find("e", 5, 10)
print(x)

8
